### ISSUE TITLE
 Add Frontend Requests to Connect with Backend for Sign-up Page

### ISSUE THREAD

**Issue by Manan-Sharma-5** [developer-student-club-thapar/DSA-Portal-Frontend#17]
To enable user registration on the sign-up page, we must add frontend requests connecting to the existing backend. The backend functionality for user registration is already in place; we need to establish communication between the frontend and backend.

Tasks to be Completed:

1. Create frontend functions or methods for sending HTTP requests (e.g., POST requests) to the appropriate backend API endpoints.
2. Ensure that the frontend requests include user registration data, such as username, email, leetcodeSessionID, password.
3. Implement error handling for the frontend requests, including handling server responses (e.g., success, error messages).
4. Verify that the front end and back end are correctly configured to communicate securely.
5. Test the sign-up functionality thoroughly to ensure successful communication with the backend.

Backend Repository Link: 

https://github.com/developer-student-club-thapar/DSA-Portal-Backend

**Comment by JurajVetrak** [comment]
Hello! Can I be assigned to this issue?

**Comment by Manan-Sharma-5** [comment]
Yes sure..

**Comment by Manan-Sharma-5** [comment]
What is the status @JurajVetrak ??

**Comment by aryan-panja** [comment]
assign the issue

**Comment by Manan-Sharma-5** [comment]
@aryan-panja status?
